In [3]:
import torch
import numpy as np

In [5]:
x = torch.empty(5,3)
print(x)

tensor([[-1.5213e+14,  4.5694e-41,  4.6640e-35],
        [ 3.0709e-41,  4.0046e-11,  1.1040e-05],
        [ 5.8253e-10,  6.6014e-07,  1.3567e-19],
        [ 1.0561e-05,  9.9618e+17,  1.3556e-19],
        [ 1.8567e-01,  7.5553e+28,  5.2839e-11]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.6490, 0.7020, 0.8955],
        [0.7187, 0.4641, 0.4788],
        [0.7049, 0.6457, 0.7081],
        [0.0450, 0.7308, 0.7155],
        [0.0624, 0.7153, 0.2340]])


In [9]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2375,  0.8225, -0.9189],
        [-0.7393, -0.6495, -0.1010],
        [-1.0387, -1.5651,  0.4021],
        [-0.7040,  0.2482,  0.6006],
        [-0.6514,  0.8330,  1.3629]])


In [15]:
y = torch.rand(5,3)
print(y)
print(x+y)

tensor([[0.6921, 0.5004, 0.9768],
        [0.2442, 0.3003, 0.6644],
        [0.8591, 0.3452, 0.2991],
        [0.9824, 0.1652, 0.9909],
        [0.3618, 0.6791, 0.1791]])
tensor([[ 0.9296,  1.3229,  0.0579],
        [-0.4950, -0.3492,  0.5634],
        [-0.1796, -1.2199,  0.7013],
        [ 0.2783,  0.4134,  1.5915],
        [-0.2895,  1.5121,  1.5421]])


In [17]:
print(torch.add(y,x))

tensor([[ 0.9296,  1.3229,  0.0579],
        [-0.4950, -0.3492,  0.5634],
        [-0.1796, -1.2199,  0.7013],
        [ 0.2783,  0.4134,  1.5915],
        [-0.2895,  1.5121,  1.5421]])


In [18]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.9296,  1.3229,  0.0579],
        [-0.4950, -0.3492,  0.5634],
        [-0.1796, -1.2199,  0.7013],
        [ 0.2783,  0.4134,  1.5915],
        [-0.2895,  1.5121,  1.5421]])


In [20]:
y.add_(x)
print(y)

tensor([[ 1.1671,  2.1455, -0.8610],
        [-1.2343, -0.9987,  0.4624],
        [-1.2182, -2.7849,  1.1034],
        [-0.4257,  0.6615,  2.1921],
        [-0.9409,  2.3452,  2.9050]])


In [24]:
print(x[:,1])
print(x)

tensor([ 0.8225, -0.6495, -1.5651,  0.2482,  0.8330])
tensor([[ 0.2375,  0.8225, -0.9189],
        [-0.7393, -0.6495, -0.1010],
        [-1.0387, -1.5651,  0.4021],
        [-0.7040,  0.2482,  0.6006],
        [-0.6514,  0.8330,  1.3629]])


In [27]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6372])
-0.6372060775756836


In [31]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [6]:
if torch.cuda.is_available():
    x = torch.randn(1)
    device = torch.device('cuda')
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu',torch.double))

tensor([1.5584], device='cuda:0')
tensor([1.5584], dtype=torch.float64)
